backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "stories"
    label: "Stories"
    folder: "stories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "team"
    label: "Team"
    folder: "team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image" }
  - name: "homepage"
    label: "Homepage Blocks"
    folder: "homepage"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Block Name", name: "block_name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }
